apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: crypto
  namespace: default
spec:
  checksum: sha256:{{ .Files.Get "crypto.py" | sha256sum }}
  deps: |
    requests
  function: |
{{ .Files.Get "crypto.py" | indent 4 }}
  handler: crypto.handler
  runtime: python2.7
  type: HTTP
